server:
  port: 8081
spring:
  profiles:
    active: dataSource
#  nacos服务
#  application:
#    name: mission-project
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848 #服务地址

#mybaatis日志
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
